# Generated by Django 5.2.7 on 2025-11-14 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('main', '0003_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to='main.product'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('promo_code', 'user', 'product')},
        ),
    ]
