# Generated by Django 5.2.7 on 2025-11-02 19:30

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Детальний опис товару в форматі Markdown'),
        ),
    ]
